### ISSUE TITLE
레시피 슬롯 클래스의 작성

### ISSUE THREAD

**Issue by 2wind** [SNUGDC/DungeonEngineer#10]
레시피는 현재 requiredTags를 가지고 매칭되는 방식으로 슬롯을 구현하고 있습니다. 한 슬롯이 and(여러 개의 태그를 모두 가져야 함), or(여러 개의 태그 중 하나만 가져도 됨), not(이 태그는 가지면 안 됨)에 해당하는 태그를 가져야 하며, 슬롯의 이름과 기능도 필요할 것입니다.
이에 따라, 각 슬롯을 슬롯의 이름인 name, 슬롯의 기능인 description,  태그 array string[] and[], or[], not[]을 가진 struct로 구현해야 합니다(레시피의 Recipe.requiredTags는 List<Slot>이 됩니다.).
내부 처리도 이에 맞추어 바꾸어야 합니다. RecipeManager 등등.

**Comment by 2wind** [comment]
지금 대략 만져 보았습니다만, 현재 구현이 "태그가 requiredTags만 존재한다"는 것을 가정해서 설계되어 있기 때문에 수정이 쉽지 않습니다. 머리가 깨질 것 같네요.

**Comment by yulcat** [comment]
추가된 함수
bool Item.HasTag(string)
bool Recipe.ContainsTag(string)
bool Slot.IsAvailable(Item)
List<Item> Slot.FilterAvailable(List<Item>)

작성의 편의를 위해서 string -> slot 암시적 타입 변환을 추가했으나, 엄밀히는 나중에 제거해야 하는 기능임

**Comment by 2wind** [comment]
일단 로직을 죄다 뜯어 고쳐서 작동하게 만들었습니다.
추가로 ApplicationManager.FilterAvailableWithoutSubItemList(List)를 이용해 조합창에서 아이템 고르는 것을 실제로 구현했습니다.
내일 혹은 모레 즈음에 and와 not태그를 추가로 이용하고, 이름과 설명도 추가해 넣으면 될 것 같습니다.

**Comment by 2wind** [comment]
이제 구현 완료되었습니다. 고마워요, 곤왜건!
