### ISSUE TITLE
JSON을 이용한 아이템, 인벤토리, 레시피, 태그의 불러오기와 저장

### ISSUE THREAD

**Issue by 2wind** [SNUGDC/DungeonEngineer#20]
일단 기술적 장애물(**GUID**)은 제거를 했습니다. 어떤 식으로, 어떤 외부 라이브러리를 써서 구현하면 좋을까요?

* 외부 라이브러리: litJson과 miniJSON을 많이 쓰는 것 같습니다.

**Comment by yulcat** [comment]
어제 내가 써본건 litJson.
toObject<T> 기능이 있어서 매우 편할듯함.

**Comment by yulcat** [comment]
litJson 이용한 아이템, 레시피, 태그 리스트 입력 구현 완료. 출력도 ToJson 쓰면 바로 가능.

**Comment by 2wind** [comment]
마지막 커밋 https://github.com/SNUGDC/DungeonEngineer/commit/23611e29fa51a943c0b21f5a75573eab120c8b9a 기준으로 테스트해봤는데 정상작동하지 않습니다. 어딘가에서 아이템을 초기 로드하지 못하는 것 같습니다.

**Comment by yulcat** [comment]
아참, 씬에 InitiateReader 컴포넌트 올려놔야 돌아감. 씬을 커밋 안했네

**Comment by yulcat** [comment]
1bbe69d08ef713f037aa9c338c917a71b3fff4f1
InitiateReader 컴포넌트를 GameManager 오브젝트에 얹은 씬을 커밋함

**Comment by 2wind** [comment]
잘 작동합니다. 감사합니다 :smile_cat:  :+1:
