### ISSUE TITLE
아이템과 태그, 조합법(레시피)의 확실한 정리 필요성

### ISSUE THREAD

**Issue by 2wind** [SNUGDC/DungeonEngineer#25]
깃헙위키 상세 문서 및 구글 드라이브 "던지니어 1차 아이템 정리"를 이용해 기획과 실제 문서를 일치시키는 작업을 하고 있습니다. 현재, 다음과 같은 문제들이 발견되었습니다:
* 기본적으로, "던지니어 1차 아이템 정리" 문서에 충분한 설명이 없음:
    * 모양 태그와 기능 태그는 서로 공유가 되는 것입니까? 예를 들어, "길쭉함" 태그를 가지고 있다면 "길쭉함" 태그는 모양 태그이자 기능 태그인 것인가요? 아니면 "길쭉함" 모양 태그가 있으면 항상 "근접무기" 기능 태그를 가지고 있는 것인지, 아니면 "길쭉함" 모양 태그가 있어도 조합을 통해 "근접무기" 기능 태그를 획득해야 하는 것인지 확실하지 않습니다.
    * 성질 태그와 기능 태그는 어떤 관계인가요? "가연성" 태그는 성질 태그인가요, 성질 태그이자 기능 태그인가요?
    * 색상 표시는 어떤 의미를 가지는 것인가요? 색상이 있는 태그는 어떤 특별한 성질이 있는 것인가요?
* "2.3 아이템 조합"에서의 의문점:
    * "아이템을 조합할 경우 하위템의 태그 중에서 모양태그와 기능태그는 사라지지만 성질태그는 그대로 유지됩니다.": 성질 태그 "가연성"과 기능 태그 "불이붙음"을 가진 나무조각들로 상자를 만들면, 그 상자는 "가연성"은 가지지만 "불이붙음" 태그는 가지지 않습니다. **이 부분은 위쪽에서 확실하게 정해지면 결론이 날 문제로 생각합니다.**
    * "여기서 투척무기와 창은 아이템을 조합하여 새롭게 생긴 태그로 창은 모양태그이고 투척무기는 기능태그입니다.": "창"이라는 태그가 따로 존재하는 것인가요? 이에 따라서...

**전체 태그 목록과 전체(적어도 부분적인) 조합식 목록이 필요합니다.**
-   [x] 전체 태그 목록이 정리되어 있어야 합니다. 
-   [x] 태그는 태그의 종류에 의해 명확하게 분류되어야 합니다.
-   [x] 기능 태그에 대해 확실한 정의가 필요합니다.
-   [x] 조합식 목록이 부분적으로나마 필요합니다.

긴 글 읽어주셔서 정말 감사합니다.

**Comment by khs9419** [comment]
길쭉함 태그가 있으면 항상 근접무기 기능태그를 가지고 있는 것입니다. 

원래는 창이라는 태그가 따로 존재하는 것으로 하려는 의도로 했지만 모양태그 항목을 채우는 것 말고는 딱히 의미가 없는 것 같아서 2차 이상 아이템의 모양 태그에 대해서는 좀 더 생각해 봐야 할 것 같습니다.

**Comment by khs9419** [comment]
가연성 태그는 성질태그입니다. 
검은색 태그는 성질태그로 항상 필기구라는 기능 태그를 가지고 있습니다. 이 태그를 추가한 이유는..... 평평함 태그와 (검은색 태그를)조합해서 그림이라는 아이템을 만들기 위해서입니다. 

성질태그와 기능태그의 가장 큰 차이점이라면 기능태그는 아이템이 가지는 고유기능을 나타내는 것으로 아이템에만 존재하는 것입니다. 예를 들면 롤에서 존야의 모래시계로 황금동상이 되는 것을 생각하면 됩니다. 
성질태그는 아이템 뿐만 아니라 몬스터도 가지는 성질입니다. 존야에 붙은 주문력 100, 방어력 50 이런것을 정성적으로 나타낸 것을 성질태그로 보면 될 것 같습니다.

**Comment by yulcat** [comment]
구현상으로 생각해보면 기능태그는 **이 아이템의 용도**인 것이고, 성질태그는 **용도 외의 특징** 이라고 생각해볼 수 있겠지. 수레를 태울 수도 있지만 수레의 용도가 불타는 것은 아닐 테니까.
아이템 조합에 재료로 들어가면 더이상 그 아이템의 용도로는 쓸 수 없게 될 거라 생각해서 기능태그로 분리하여 조합시 없어지도록 한 것. 아이템 리스트나 조합식 짤 때도 유의하고 만들어야 될 것 같네.

**Comment by 2wind** [comment]
감사합니다. 일단 기획에 맞추어서 태그와 조합법, 1차 아이템 목록을 json 파일로 정리했습니다.
그런데 1차 아이템 중에 일견 합리적이지 않아 보이는 부분이 조금 보여 질문드립니다.
* 1차 아이템은 (기능 태그를 제외하면) 태그를 각기 한 종류씩, 두 개만 가지는 것이 맞나요?
* 현재 1차 아이템에서 밥알과 레몬, 감자는 식량이 아니며, 쇠로 된 아이템와 은박지는 전기 전도성이 없습니다. 유저가 이런 상황을 보고 "비합리하다"라고 느끼지 않을까요? 예를 들어 유저가 HP를 높이기 위해 감자를 먹으려 하지만 "먹을 수 없는" 상황이 된다면 조금 이상하게 느낄 것 같습니다.

**Comment by khs9419** [comment]
ㄴㄴ 일단 편의상 2개로 정리해 놓은 거고 아이템 마다 필요하다면 태그를 추가할 생각입니다.

**Comment by 2wind** [comment]
원하실 때마다 JSON 파일을 직접 편집하셔도 되고, 문서로 남겨 주셔도 좋습니다.

**Comment by 2wind** [comment]
어느 정도 정리가 된 것 같으므로 닫습니다.
