### ISSUE TITLE
기능이 있는 아이템은 아이템창에서 기능을 실행할 수 있어야 함

### ISSUE THREAD

**Issue by 2wind** [SNUGDC/DungeonEngineer#8]
(필드와 관련해) "function"을 가진 아이템에 대해 각기 기능 버튼을 아이템창에서 보이게 해야 합니다. 또한 버튼을 누르면 필드와 연동되어 다른 함수를 호출할 수 있도록 디자인되어야 합니다. 적절하게 구현만 해 둔다면 규호형이 적절하게 써 먹을 수 있을 겁니다.

**Comment by 2wind** [comment]
일단 이슈 #10 이 완료된 뒤에, 해결하는 것으로 합시다.

**Comment by 2wind** [comment]
이슈 #10 이 완료되었으므로, 이제 기능 태그를 따로 빼서 인식하도록 만들 수 있을 것 같습니다. 우선순위 에 대한 결정이 필요하겠군요(ex. flammable과 edible이 같이 있으면, 아이템창에는 어느 쪽이 보여야 할까요?).

**Comment by 2wind** [comment]
기능과 관련해서, 현재 기획에서는 "아이템 상세 정보창에서 태그를 클릭하면" 그 태그에 상응하는 동작이 일어난다고 서술하고 있습니다. 아이템 상세 정보창에서는 지금 텍스트만 보여지는데, 이를 버튼들의 일련으로 바꿔야겠군요.

**Comment by yulcat** [comment]
앗, 그건 반대. UI상에서 기능과 정보가 혼용되어선 안됨. 기획서가 잘못 쓰인 것으로.

**Comment by khs9419** [comment]
그... 렇겠네요. 기능과 정보가 혼용되면 안되고 아이템창에서 아이템을 눌렀을때 사용 혹은 장착 버튼을 통해서 사용하게 하고 태그는 아이템 상세 정보창에서 알수 있도록 해야 겠군요

**Comment by 2wind** [comment]
현재 기능 태그는 다양한 종류가 존재합니다. 이 때문에 한 가지 문제가 발생하게 됩니다. 한 아이템이 여러 기능을 가지게 된다면, 그 기능들은 어떻게 접근되어야 할까요? 가설적으로, 한 아이템이 15개 기능 태그를 가지게 된다면 어떻게 기능을 사용하도록 해야 할까요?
추가적으로, 아이템의 기능을 사용하는 화면은 어디가 되어야 할까요? 아이템 창에서 바로? 아이템의 상세정보창에서? (설치된 아이템의 경우는, "탐색 모드"를 활성화한 상태에서, 필드에서 아이템을 선택하면 나오는 창이 될 겁니다)

**Comment by khs9419** [comment]
아이템의 기능을 사용하는 화면은 아이템창에서 아이템을 클릭했을 때 사용하도록 합니다. 
설치아이템의 경우에는 설치한 이후에 필드에 있는 아이템을 클릭하여 사용 버튼을 누르게 하면 될 것 같습니다. 
장비 아이템의 경우에는 아이템창에서 클릭했을 때 장착 버튼을 누르면 장착되고 그 상태에서 화면을 누르면 공격 모션이 나타는 것으로 하는게 좋을 것 같습니다. 
장비 아이템의 다른 기능 (너도한방나도한방 태그 등등)을 사용하려면 장착 버튼 밑에 사용 버튼을 만들어서 누르도록 하면 될 것 같습니다. 
몇몇 기능태그 (투척무기 등등) 는 패시브성을 가지는 것들도 있는데 그런 것들은 on/off로 해서 기능태그를 좀 더 다양화 할 수도 있을 것 같네요

**Comment by yulcat** [comment]
액티브 기능 태그를 제한한다고 해서 문제가 해결되진 않음. 기능 태그가 아니지만 사용가능한 태그가 있을 수도 있고 (먹을 수 있음, 불에 탐 등등) 패시브도 결국 장착 혹은 설치를 해야 하기 때문.
아이템 리스트에서 바로 기능을 수행하기보다, 사용가능한 태그가 하나 이상 있는 아이템에 **사용가능** 아이콘을 띄워서 사용 가능한 아이템임을 알려 주고, **아이템을 눌러서 세부 창이 떴을 때** 기능 버튼들을 표시해 주는 것이 좋을 듯.

**Comment by yulcat** [comment]
그리고 전투에 대해서는 뭔가 생각하는 모습이 다르다고 생각되는데. 이동과 별개로 공격이라는 액션이 있지는 않고, 몬스터가 있는 방향으로 이동 화살표를 누르면 이동 대신 공격이 나갈 예정이었어. 맞는 거야 그냥 맞는 거고...
장비는 보통 게임들에서 장비 장착하듯이 캐릭터에 장착하는 것. 장착하고 있으면 계속 전투시에 효과를 받음. 장비 아이템에 다른 기능이 있다면.... 음 좀 사용법이 복잡해질 것 같다.

**Comment by 2wind** [comment]
기능 구현을 위한 준비를 마쳤습니다. ItemManager나 메인 게임 스크립트 쪽에서 함수를 제공하면, 간단한 분기처리+조건문으로 (아이템 창에서) 기능 실행이 가능합니다. 0db710e6b9ae6789c71db80792b7ca7d2f018f9a 에서 FunctionOnClick() 함수를 체크해주세요.

**Comment by 2wind** [comment]
기능이 실행됩니다.
